const menuUrl =
  "https://theswanatstreatley.co.uk/wp-content/uploads/2026/04/Summer-26-Drinks-Menu-HIGH-110x250-WEB.pdf";
const venueUrl = "https://theswanatstreatley.co.uk/food/menu/drinks/";

const wineBodies = {
  "canal-grando-prosecco": "Light",
  "sacchetto-prosecco-rose": "Light",
  "andre-delorme-cremant": "Medium",
  "nyetimber-classic-cuvee": "Medium",
  "nyetimber-rose": "Medium",
  "veuve-clicquot-yellow-label": "Medium · structured",
  "bollinger-special-cuvee": "Medium–full",
  "laurent-perrier-cuvee-rose": "Medium",
  "ruinart-blanc-de-blancs": "Medium",
  "krug-grande-cuvee-173": "Full",
  "real-sparkling-dry-white": "Light",
  "chablis-thomas-labille": "Light–medium",
  "picpoul-tournee-du-sud": "Light",
  "sancerre-merlin-cherrier": "Light–medium",
  "les-boules-blanc": "Light",
  "gavi-michele-chiarlo": "Medium",
  "pinot-grigio-riff-alois-lageder": "Light–medium",
  "assyrtiko-terre-grec": "Medium",
  "sauvignon-blanc-tournee-du-sud": "Light",
  "chardonnay-les-sardines": "Medium",
  "chenin-blanc-wild-garden": "Light",
  "sauvignon-blanc-saint-clair": "Medium–full",
  "la-crema-monterey-chardonnay": "Medium–full",
  "viognier-berton-vineyard": "Full",
  "pouilly-fuisse-nadine-ferrand": "Full",
  "meursault-michel-gayot": "Full",
  "pinot-grigio-blush-novita": "Light",
  "m-de-minuty": "Light–medium",
  "whispering-angel": "Light",
  "syrah-vermentino-rose-campuget": "Medium",
  "madame-f-rose": "Light",
  "marie-christine-aumerade": "Light",
  "rock-angel": "Medium–full",
  "merlot-undurraga": "Medium",
  "sangiovese-novita": "Light",
  "pinot-noir-sibaris": "Medium",
  "syrah-grenache-campuget": "Medium–full",
  "malbec-andeluna": "Full",
  "primitivo-san-marzano": "Full",
  "medoc-goulee-cos-destournel": "Full",
  "rioja-reserva-hugonell": "Medium",
  "pinotage-wild-garden": "Light–medium",
  "saint-emilion-chateau-gravillon": "Medium–full",
  "barolo-san-silvestro": "Full",
  "malbec-salentein-barrel-selection": "Full",
  "rosso-montalcino-poggio-mura": "Medium–full",
  "chianti-classico-carpineto": "Medium–full",
  "pinot-noir-sylvain-debord": "Medium",
  "cabernet-freemark-abbey": "Full"
};

const wineRows = [
  {
    id: "canal-grando-prosecco",
    name: "Prosecco, Canal Grando NV",
    group: "sparkling",
    groupLabel: "Sparkling",
    style: "Crisp & refreshing",
    sweetness: "Extra Dry · softly fruity",
    origin: "Veneto, Italy",
    notes: "Citrus, crisp, refreshing",
    price: "125ml £8.80 · Bottle £39",
    sourceUrl: menuUrl
  },
  {
    id: "sacchetto-prosecco-rose",
    name: "Prosecco Rosé, Sacchetto",
    group: "sparkling",
    groupLabel: "Sparkling",
    style: "Rosé Prosecco",
    sweetness: "Extra Dry · softly fruity",
    origin: "Veneto, Italy",
    notes: "Strawberry, red berries, floral",
    price: "Bottle £41",
    sourceUrl: venueUrl
  },
  {
    id: "andre-delorme-cremant",
    name: "Crémant de Bourgogne, André Delorme NV",
    group: "sparkling",
    groupLabel: "Sparkling",
    style: "Crémant",
    sweetness: "Brut · dry",
    origin: "Burgundy, France",
    notes: "Crisp apple, creamy, brioche",
    price: "Bottle £53",
    sourceUrl: venueUrl
  },
  {
    id: "nyetimber-classic-cuvee",
    name: "Nyetimber, Classic Cuvée MV",
    group: "sparkling",
    groupLabel: "Sparkling",
    style: "English sparkling",
    sweetness: "Brut · dry",
    origin: "West Sussex, England",
    notes: "Pastry, almond, baked apples",
    price: "125ml £15.30 · Bottle £68 · Magnum £125",
    sourceUrl: menuUrl
  },
  {
    id: "nyetimber-rose",
    name: "Nyetimber, Rosé MV",
    group: "sparkling",
    groupLabel: "Sparkling",
    style: "English sparkling rosé",
    sweetness: "Brut · dry",
    origin: "West Sussex, England",
    notes: "Elegant, Eton mess, summer berries",
    price: "Bottle £72",
    sourceUrl: venueUrl
  },
  {
    id: "veuve-clicquot-yellow-label",
    name: "Veuve Clicquot, Yellow Label NV",
    group: "sparkling",
    groupLabel: "Sparkling",
    style: "Champagne",
    sweetness: "Brut · dry",
    origin: "Champagne, France",
    notes: "Rich yellow fruits, pear, shortbread",
    price: "125ml £21 · Bottle £93 · Magnum £175",
    sourceUrl: menuUrl
  },
  {
    id: "bollinger-special-cuvee",
    name: "Bollinger, Special Cuvée NV",
    group: "sparkling",
    groupLabel: "Sparkling",
    style: "Champagne",
    sweetness: "Brut · dry",
    origin: "Champagne, France",
    notes: "Stone fruit, toasty, creamy finish",
    price: "Bottle £120",
    sourceUrl: venueUrl
  },
  {
    id: "laurent-perrier-cuvee-rose",
    name: "Laurent-Perrier, Cuvée Rosé NV",
    group: "sparkling",
    groupLabel: "Sparkling",
    style: "Rosé Champagne",
    sweetness: "Brut · dry",
    origin: "Champagne, France",
    notes: "Delicate, redcurrants, raspberries",
    price: "Bottle £150",
    sourceUrl: venueUrl
  },
  {
    id: "ruinart-blanc-de-blancs",
    name: "Ruinart, Blanc de Blancs NV",
    group: "sparkling",
    groupLabel: "Sparkling",
    style: "Blanc de Blancs Champagne",
    sweetness: "Brut · dry",
    origin: "Champagne, France",
    notes: "Spice, bright citrus, white flowers",
    price: "Bottle £180",
    sourceUrl: venueUrl
  },
  {
    id: "krug-grande-cuvee-173",
    name: "Krug, Grande Cuvée Edition 173 NV",
    group: "sparkling",
    groupLabel: "Sparkling",
    style: "Prestige Champagne",
    sweetness: "Brut · dry",
    origin: "Champagne, France",
    notes: "Complex, hazelnut, lemon curd",
    price: "Bottle £405",
    sourceUrl: venueUrl
  },
  {
    id: "real-sparkling-dry-white",
    name: "REAL Sparkling Dry White",
    group: "alcohol-free",
    groupLabel: "Alcohol-free sparkling",
    style: "Slow-fermented sparkling tea · 0.5% ABV",
    sweetness: "Dry · alcohol-free",
    origin: "England",
    notes: "Light and fragrant, lemon meringue, dry nutty finish",
    price: "125ml £7.90 · Bottle £35",
    sourceUrl: "https://realalcoholfree.com/products/sparkling-tea-dry-dragon-250ml-12-case"
  },
  {
    id: "chablis-thomas-labille",
    name: "Chablis, Thomas Labille",
    group: "white",
    groupLabel: "White",
    style: "Crisp & vibrant",
    sweetness: "Bone dry",
    origin: "Burgundy, France",
    notes: "Mouthwatering, vibrant citrus",
    price: "Bottle £67",
    sourceUrl: venueUrl
  },
  {
    id: "picpoul-tournee-du-sud",
    name: "Picpoul de Pinet, Tournée du Sud",
    group: "white",
    groupLabel: "White",
    style: "Crisp & vibrant",
    sweetness: "Bone dry",
    origin: "Languedoc, France",
    notes: "Lemon and lime, grapefruit, acacia flowers",
    price: "175ml £12.60 · 250ml £17.30 · Bottle £45",
    sourceUrl: menuUrl
  },
  {
    id: "sancerre-merlin-cherrier",
    name: "Sancerre, Domaine Merlin-Cherrier",
    group: "white",
    groupLabel: "White",
    style: "Crisp & vibrant",
    sweetness: "Dry",
    origin: "Loire, France",
    notes: "Aromatic, finessed, long refreshing finish",
    price: "Bottle £70",
    sourceUrl: venueUrl
  },
  {
    id: "les-boules-blanc",
    name: "Les Boules Blanc",
    group: "white",
    groupLabel: "White",
    style: "Crisp & vibrant",
    sweetness: "Dry to just off-dry",
    origin: "South West France",
    notes: "Citrus, apple, floral",
    price: "175ml £8.70 · 250ml £11.90 · Bottle £31",
    sourceUrl: menuUrl
  },
  {
    id: "gavi-michele-chiarlo",
    name: "Gavi, Michele Chiarlo",
    group: "white",
    groupLabel: "White",
    style: "Crisp & vibrant",
    sweetness: "Dry",
    origin: "Piedmont, Italy",
    notes: "Expressive, exotic fruits, lemon zest",
    price: "175ml £15.40 · 250ml £21.10 · Bottle £55",
    sourceUrl: menuUrl
  },
  {
    id: "pinot-grigio-riff-alois-lageder",
    name: "Pinot Grigio, Riff, Alois Lageder",
    group: "white",
    groupLabel: "White",
    style: "Crisp & vibrant · organic",
    sweetness: "Dry",
    origin: "Veneto, Italy",
    notes: "Pear, citrus, green apples",
    price: "175ml £12.10 · 250ml £16.50 · Bottle £43",
    sourceUrl: menuUrl
  },
  {
    id: "assyrtiko-terre-grec",
    name: "Assyrtiko, Terre Grec",
    group: "white",
    groupLabel: "White",
    style: "Fruity & bright",
    sweetness: "Dry",
    origin: "Thessaly, Greece",
    notes: "Vibrant lime, orange leaf, maritime minerality",
    price: "175ml £12.40 · 250ml £16.90 · Bottle £44",
    sourceUrl: menuUrl
  },
  {
    id: "sauvignon-blanc-tournee-du-sud",
    name: "Sauvignon Blanc, Tournée du Sud",
    group: "white",
    groupLabel: "White",
    style: "Fruity & bright",
    sweetness: "Dry",
    origin: "Languedoc, France",
    notes: "Zesty, grapefruit, pineapple",
    price: "175ml £10.40 · 250ml £14.20 · Bottle £37",
    sourceUrl: menuUrl
  },
  {
    id: "chardonnay-les-sardines",
    name: "Chardonnay, Les Sardines",
    group: "white",
    groupLabel: "White",
    style: "Fruity & bright",
    sweetness: "Dry",
    origin: "Roussillon, France",
    notes: "White peach, stone fruits, refreshing coastal influence",
    price: "175ml £10.10 · 250ml £13.80 · Bottle £36",
    sourceUrl: menuUrl
  },
  {
    id: "chenin-blanc-wild-garden",
    name: "Chenin Blanc, Wild Garden",
    group: "white",
    groupLabel: "White",
    style: "Fruity & bright",
    sweetness: "Off-dry",
    origin: "Western Cape, South Africa",
    notes: "Ripe mango, tropical, fruity",
    price: "175ml £9.80 · 250ml £13.50 · Bottle £35",
    sourceUrl: menuUrl
  },
  {
    id: "sauvignon-blanc-saint-clair",
    name: "Sauvignon Blanc, Saint Clair",
    group: "white",
    groupLabel: "White",
    style: "Fruity & bright",
    sweetness: "Dry",
    origin: "Marlborough, New Zealand",
    notes: "Passionfruit, gooseberry, herbaceous notes",
    price: "175ml £12 · 250ml £17.20 · Bottle £49",
    sourceUrl: menuUrl
  },
  {
    id: "la-crema-monterey-chardonnay",
    name: "Chardonnay, Monterey, La Crema",
    group: "white",
    groupLabel: "White",
    style: "Rich & textured",
    sweetness: "Dry",
    origin: "California, USA",
    notes: "Tangerine, oak spice, coastal freshness",
    price: "Bottle £69",
    sourceUrl: venueUrl
  },
  {
    id: "viognier-berton-vineyard",
    name: "Viognier, Berton Vineyard",
    group: "white",
    groupLabel: "White",
    style: "Rich & textured",
    sweetness: "Dry · fruit-rich",
    origin: "New South Wales, Australia",
    notes: "Nectarine, melon, orange blossom",
    price: "175ml £11.50 · 250ml £15.80 · Bottle £41",
    sourceUrl: menuUrl
  },
  {
    id: "pouilly-fuisse-nadine-ferrand",
    name: "Pouilly-Fuissé 1er Cru Prestige, Domaine Nadine Ferrand",
    group: "white",
    groupLabel: "White",
    style: "Rich & textured",
    sweetness: "Dry",
    origin: "Burgundy, France",
    notes: "Rich and buttery, ripe pineapple, hints of vanilla",
    price: "Bottle £99",
    sourceUrl: venueUrl
  },
  {
    id: "meursault-michel-gayot",
    name: "Meursault, Michel Gayot",
    group: "white",
    groupLabel: "White",
    style: "Rich & textured",
    sweetness: "Dry",
    origin: "Burgundy, France",
    notes: "Toasted almond, whole fruit, delicate florals",
    price: "Bottle £170",
    sourceUrl: venueUrl
  },
  {
    id: "pinot-grigio-blush-novita",
    name: "Pinot Grigio Blush, Novità",
    group: "rose",
    groupLabel: "Rosé",
    style: "Light & fruity",
    sweetness: "Off-dry",
    origin: "Veneto, Italy",
    notes: "Fruity, cherries, strawberry",
    price: "175ml £10.10 · 250ml £13.80 · Bottle £36",
    sourceUrl: menuUrl
  },
  {
    id: "m-de-minuty",
    name: "M de Minuty",
    group: "rose",
    groupLabel: "Rosé",
    style: "Pale Provence rosé",
    sweetness: "Dry",
    origin: "Provence, France",
    notes: "Soft summer fruits, peach, orange peel",
    price: "175ml £16.60 · 250ml £22.70 · Bottle £59",
    sourceUrl: menuUrl
  },
  {
    id: "whispering-angel",
    name: "Whispering Angel",
    group: "rose",
    groupLabel: "Rosé",
    style: "Pale Provence rosé",
    sweetness: "Dry",
    origin: "Provence, France",
    notes: "Ripe red berries, strawberries, floral",
    price: "Bottle £69",
    sourceUrl: venueUrl
  },
  {
    id: "syrah-vermentino-rose-campuget",
    name: "Syrah Vermentino Rosé, Château de Campuget",
    group: "rose",
    groupLabel: "Rosé",
    style: "Citrus-led rosé",
    sweetness: "Dry to lightly off-dry",
    origin: "Languedoc, France",
    notes: "Redcurrants, citrus, grapefruit",
    price: "175ml £14.90 · 250ml £20.40 · Bottle £53",
    sourceUrl: menuUrl
  },
  {
    id: "madame-f-rose",
    name: "Madame F Rosé",
    group: "rose",
    groupLabel: "Rosé",
    style: "Juicy & lightly spiced",
    sweetness: "Dry",
    origin: "Méditerranée, France",
    notes: "Juicy red fruits, peach, subtle white pepper",
    price: "175ml £11.50 · 250ml £15.80 · Bottle £41",
    sourceUrl: menuUrl
  },
  {
    id: "marie-christine-aumerade",
    name: "Cru Classé, Marie Christine, Château de l’Aumérade",
    group: "rose",
    groupLabel: "Rosé",
    style: "Classic Provence rosé",
    sweetness: "Dry",
    origin: "Provence, France",
    notes: "Refined, classic Mediterranean, red berries",
    price: "Bottle £57",
    sourceUrl: venueUrl
  },
  {
    id: "rock-angel",
    name: "Rock Angel",
    group: "rose",
    groupLabel: "Rosé",
    style: "Rich & full rosé",
    sweetness: "Dry",
    origin: "Provence, France",
    notes: "Rich and bold, candied raspberries, rose petals",
    price: "Bottle £79",
    sourceUrl: venueUrl
  },
  {
    id: "merlot-undurraga",
    name: "Merlot, Undurraga",
    group: "red",
    groupLabel: "Red",
    style: "Soft & juicy",
    sweetness: "Dry",
    origin: "Central Valley, Chile",
    notes: "Juicy plums, warming spice, smooth",
    price: "175ml £11.20 · 250ml £15.40 · Bottle £40",
    sourceUrl: menuUrl
  },
  {
    id: "sangiovese-novita",
    name: "Sangiovese, Novità",
    group: "red",
    groupLabel: "Red",
    style: "Soft & juicy",
    sweetness: "Dry to just off-dry",
    origin: "Emilia-Romagna, Italy",
    notes: "Juicy redcurrant, red plums, cherries",
    price: "175ml £9 · 250ml £12.30 · Bottle £32",
    sourceUrl: menuUrl
  },
  {
    id: "pinot-noir-sibaris",
    name: "Pinot Noir Gran Reserva, Sibaris",
    group: "red",
    groupLabel: "Red",
    style: "Soft & juicy",
    sweetness: "Dry",
    origin: "Valle de Leyda, Chile",
    notes: "Morello cherry, raspberry, smoky herbs",
    price: "175ml £13.20 · 250ml £18.10 · Bottle £47",
    sourceUrl: menuUrl
  },
  {
    id: "syrah-grenache-campuget",
    name: "Syrah-Grenache, Château de Campuget",
    group: "red",
    groupLabel: "Red",
    style: "Soft & juicy",
    sweetness: "Dry",
    origin: "Languedoc, France",
    notes: "Spicy red fruits, dark cherry, blueberries",
    price: "175ml £10.70 · 250ml £14.60 · Bottle £38",
    sourceUrl: menuUrl
  },
  {
    id: "malbec-andeluna",
    name: "Malbec, Andeluna",
    group: "red",
    groupLabel: "Red",
    style: "Soft & juicy",
    sweetness: "Dry",
    origin: "Mendoza, Argentina",
    notes: "Ripe blackberry, silky, floral notes",
    price: "175ml £12 · 250ml £17.20 · Bottle £49",
    sourceUrl: menuUrl
  },
  {
    id: "primitivo-san-marzano",
    name: "Primitivo, San Marzano",
    group: "red",
    groupLabel: "Red",
    style: "Spicy & smooth",
    sweetness: "Dry · ripe fruit",
    origin: "Puglia, Italy",
    notes: "Ripe prune, dark cherry, vanilla",
    price: "175ml £12.40 · 250ml £16.90 · Bottle £44",
    sourceUrl: menuUrl
  },
  {
    id: "medoc-goulee-cos-destournel",
    name: "Médoc, Goulée by Cos d’Estournel",
    group: "red",
    groupLabel: "Red",
    style: "Spicy & smooth",
    sweetness: "Dry",
    origin: "Bordeaux, France",
    notes: "Opulent, dense red and black berries, spice",
    price: "Bottle £88",
    sourceUrl: venueUrl
  },
  {
    id: "rioja-reserva-hugonell",
    name: "Rioja Reserva, Hugonell",
    group: "red",
    groupLabel: "Red",
    style: "Spicy & smooth",
    sweetness: "Dry",
    origin: "Rioja, Spain",
    notes: "Red berries, tobacco, spicy oak",
    price: "175ml £14.90 · 250ml £20.40 · Bottle £53",
    sourceUrl: menuUrl
  },
  {
    id: "pinotage-wild-garden",
    name: "Pinotage, Wild Garden",
    group: "red",
    groupLabel: "Red",
    style: "Spicy & smooth",
    sweetness: "Dry",
    origin: "Cape Coast, South Africa",
    notes: "Ripe plum, bramble, hint of smokiness",
    price: "175ml £9.80 · 250ml £13.50 · Bottle £35",
    sourceUrl: menuUrl
  },
  {
    id: "saint-emilion-chateau-gravillon",
    name: "Saint-Émilion, Château du Gravillon",
    group: "red",
    groupLabel: "Red",
    style: "Spicy & smooth",
    sweetness: "Dry",
    origin: "Bordeaux, France",
    notes: "Ripe plum, blackberry, silky tannins",
    price: "Bottle £67",
    sourceUrl: venueUrl
  },
  {
    id: "barolo-san-silvestro",
    name: "Barolo, San Silvestro",
    group: "red",
    groupLabel: "Red",
    style: "Bold & robust",
    sweetness: "Dry",
    origin: "Piedmont, Italy",
    notes: "Dried fruit, roses, sweet tannins",
    price: "Bottle £81",
    sourceUrl: venueUrl
  },
  {
    id: "malbec-salentein-barrel-selection",
    name: "Malbec Barrel Selection, Salentein",
    group: "red",
    groupLabel: "Red",
    style: "Bold & robust",
    sweetness: "Dry",
    origin: "Valle de Uco, Argentina",
    notes: "Blueberry, redcurrant, savoury finish",
    price: "Bottle £59",
    sourceUrl: venueUrl
  },
  {
    id: "rosso-montalcino-poggio-mura",
    name: "Rosso di Montalcino, Poggio alle Mura, Banfi",
    group: "red",
    groupLabel: "Red",
    style: "Bold & robust",
    sweetness: "Dry",
    origin: "Tuscany, Italy",
    notes: "Complex, plum jam, liquorice",
    price: "Bottle £75",
    sourceUrl: venueUrl
  },
  {
    id: "chianti-classico-carpineto",
    name: "Chianti Classico, Carpineto",
    group: "red",
    groupLabel: "Red",
    style: "Bold & robust",
    sweetness: "Dry",
    origin: "Tuscany, Italy",
    notes: "Classic, sour red cherry, dark chocolate",
    price: "Bottle £63",
    sourceUrl: venueUrl
  },
  {
    id: "pinot-noir-sylvain-debord",
    name: "Pinot Noir, Sylvain Debord",
    group: "red",
    groupLabel: "Red",
    style: "Bold & robust",
    sweetness: "Dry",
    origin: "Burgundy, France",
    notes: "Aromatic, wild raspberries, cloves",
    price: "Bottle £71",
    sourceUrl: venueUrl
  },
  {
    id: "cabernet-freemark-abbey",
    name: "Cabernet Sauvignon, Napa Valley, Freemark Abbey",
    group: "red",
    groupLabel: "Red",
    style: "Bold & robust",
    sweetness: "Dry",
    origin: "California, USA",
    notes: "Blackcurrants, toasty cedar, mocha",
    price: "Bottle £150",
    sourceUrl: venueUrl
  }
];

export const wines = wineRows.map((wine) => ({
  ...wine,
  body: wineBodies[wine.id] ?? "Medium"
}));

export const beers = [
  {
    id: "asahi-super-dry",
    name: "Asahi Super Dry",
    group: "draught",
    groupLabel: "Draught",
    style: "Japanese lager",
    profile: "Light, dry & crisp",
    abv: "5%",
    format: "Draught",
    price: "½ pint £3.90 · Pint £7.80",
    sourceUrl: menuUrl
  },
  {
    id: "freedom-session-ipa",
    name: "Freedom Session IPA",
    group: "draught",
    groupLabel: "Draught",
    style: "Session IPA",
    profile: "Light-bodied, citrus & hoppy",
    abv: "4.3%",
    format: "Draught",
    price: "½ pint £4 · Pint £8",
    sourceUrl: menuUrl
  },
  {
    id: "guinness-draught",
    name: "Guinness",
    group: "draught",
    groupLabel: "Draught",
    style: "Irish dry stout",
    profile: "Dark, smooth & roasted",
    abv: "4.2%",
    format: "Draught",
    price: "½ pint £3.90 · Pint £7.70",
    sourceUrl: menuUrl
  },
  {
    id: "aspall-cyder",
    name: "Aspall Cyder",
    group: "draught",
    groupLabel: "Draught",
    style: "Dry cider",
    profile: "Crisp apple, dry finish",
    abv: "5.5%",
    format: "Draught",
    price: "½ pint £3.80 · Pint £7.60",
    sourceUrl: menuUrl
  },
  {
    id: "curious-brew-lager",
    name: "Curious Brew Lager",
    group: "packaged",
    groupLabel: "Packaged",
    style: "Lager",
    profile: "Clean, fruity & aromatic",
    abv: "4.7%",
    format: "330ml",
    price: "£6.30",
    sourceUrl: "https://curiousbrewery.com/product/curious-brew/"
  },
  {
    id: "jubel-peach-lager",
    name: "Jubel Peach Lager",
    group: "packaged",
    groupLabel: "Packaged",
    style: "Peach lager",
    profile: "Light, crisp & peachy",
    abv: "4%",
    format: "330ml",
    price: "£6.80",
    sourceUrl: "https://jubelbeer.com/products/can/peach"
  },
  {
    id: "small-beer-hazy-ipa",
    name: "Small Beer Hazy IPA",
    group: "packaged",
    groupLabel: "Packaged",
    style: "Hazy IPA",
    profile: "Light, tropical & softly bitter",
    abv: "2.6%",
    format: "330ml",
    price: "£6.80",
    sourceUrl: "https://theoriginalsmallbeer.com/products/hazy-ipa"
  },
  {
    id: "howies-berry-cider",
    name: "Howies Berries Cider",
    group: "packaged",
    groupLabel: "Packaged",
    style: "Fruit cider",
    profile: "Sweet berry, crisp apple finish",
    abv: "3.4%",
    format: "500ml",
    price: "£7.30",
    sourceUrl: "https://howiescider.com/products/berry"
  },
  {
    id: "howies-peach-cider",
    name: "Howies Peach Cider",
    group: "packaged",
    groupLabel: "Packaged",
    style: "Fruit cider",
    profile: "Medium-bodied, sweet & tangy",
    abv: "3.4%",
    format: "500ml",
    price: "£7.30",
    sourceUrl: "https://howiescider.com/products/peach"
  },
  {
    id: "peroni-zero",
    name: "Peroni Nastro Azzurro 0.0%",
    group: "alcohol-free",
    groupLabel: "Alcohol-free",
    style: "Alcohol-free lager",
    profile: "Light, crisp & gently bitter",
    abv: "0.0%",
    format: "330ml",
    price: "£5.70",
    sourceUrl: menuUrl
  },
  {
    id: "big-drop-paradiso",
    name: "Big Drop Paradiso Citra IPA",
    group: "alcohol-free",
    groupLabel: "Alcohol-free",
    style: "Citra IPA",
    profile: "Citrus, tropical fruit & firm bitterness",
    abv: "0.5%",
    format: "330ml",
    price: "£5.90",
    sourceUrl: "https://shop.bigdropbrew.com/products/big-drop-paradiso-citra-ipa-300ml-can"
  },
  {
    id: "bero-kingston-golden-pils",
    name: "BERO Kingston Golden Pils",
    group: "alcohol-free",
    groupLabel: "Alcohol-free",
    style: "Golden pilsner",
    profile: "Malty, herbal & moderately bitter",
    abv: "0.48%",
    format: "330ml",
    price: "£5.90",
    sourceUrl: "https://berobrewing.com/products/kingston-golden-pils"
  },
  {
    id: "bero-edge-hill-hazy-ipa",
    name: "BERO Edge Hill Hazy IPA",
    group: "alcohol-free",
    groupLabel: "Alcohol-free",
    style: "Hazy IPA",
    profile: "Soft, tropical, citrus & hoppy",
    abv: "0.48%",
    format: "330ml",
    price: "£5.90",
    sourceUrl: "https://berobrewing.com/products/edge-hill-hazy-ipa"
  },
  {
    id: "guinness-zero",
    name: "Guinness 0.0%",
    group: "alcohol-free",
    groupLabel: "Alcohol-free",
    style: "Alcohol-free stout",
    profile: "Dark, smooth & roasted",
    abv: "0.0%",
    format: "538ml",
    price: "£7",
    sourceUrl: menuUrl
  }
];
